# Generated by Django 4.1.1 on 2022-09-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_booksrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksRecord',
        ),
    ]
